### ISSUE TITLE
Issue with process.py

### ISSUE THREAD

**Issue by luke2997** [meszlili96/PanNukeChallenge#5]
Hello, I have successfully run train.py and infer.py but after I transform the folds into png and then I get an output file of 2703 files which is used in process.py, I get the following error indicating that there are too many files. I'm wondering if I used the wrong files? My self.inf_data_dir in config is png files from fold3, meanwhile self.inf_output_dir are .mat files.

```
Traceback (most recent call last):
  File "process.py", line 96, in <module>
    overlaid_output = visualize_instances(pred_type, img)
  File "/lustre/home/acct-clsyzs/clsyzs/Luke/hvPan/PanNuke/src/misc/viz_utils.py", line 56, in visualize_instances
    contours,_ = cv2.findContours(inst_map_crop, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)
```

**Comment by luke2997** [comment]
Used the wrong opencv version

**Comment by meszlili96** [comment]
Hi, I'm glad you managed to solve it and I'm really sorry that I didn't respond earlier. If you run into other problems, I'll try to be quicker with my response.

**Comment by luke2997** [comment]
@meszlili96 Thank you! How exactly should I run step 14 exactly? I didn't edit the file, but get an error when I run this:

```
python run.py -- '--/Luke/PanNuke/src/PanNuke_Metrics/fold3/masks.npy' --' --/Luke/PanNuke/src/output_pannuke/v1.0/np_hv/' -- '--/Luke/PanNuke/src/PanNuke_Metrics'
```
The error is

```
File "run.py", line 160, in <module>
    args = docopt(__doc__, version='PanNuke Evaluation v1.0')
TypeError: 'module' object is not callable
```

**Comment by meszlili96** [comment]
My first guess would be that the `true_path` is causing the problem as `masks.npy` is added to the path in the code: https://github.com/meszlili96/PanNukeChallenge/blob/ad4c8428eed20e9fa14e728b4e8a74ddbd0f1736/src/metrics/run.py#L70

Otherwise, are you sure the paths are correct? If so, my suggestion would be to run it like this:
```
python run.py --true_path='--/Luke/PanNuke/src/PanNuke_Metrics/fold3' --pred_path=' --/Luke/PanNuke/src/output_pannuke/v1.0/np_hv/' --save_path='--/Luke/PanNuke/src/PanNuke_Metrics'
```
I hope this solves it.

**Comment by luke2997** [comment]
Thanks for your timely reply. So this is what is inside each folder:

**true path**: Ground Truths of the original images in fold3 i.e. testing set. This folder contains both masks.npy and type.npy otherwise `types_path = os.path.join(true_root,'types.npy')` does not work.

**pred path**: The matlab output file from transform_for_metrics.py

**Comment by luke2997** [comment]
@meszlili96  OK i fixed the initial error, i need to change the import to "from docopt import docopt". However...when the csv file returns I get 99.9 PQ for each gland which is clearly **wrong** indicating it is comparing the same image. Also it gives an error that `IndexError: list index out of range`. Are the directories that I stated above correct?

**Comment by meszlili96** [comment]
Indeed the `true_path` should contain both the masks and types. `pred_path` should contain the output of `transform_for_metrics.py`, but note that you need `masks.npy` in the folder not matlab.

Also, don't forget step 13:

> Run `src/metrics/remove_lostids_from_gt_fold3.py` and `src/metrics/remove_lostids_from_gt_fold1.py` to remove the lost files from the ground truth.

Leaving out this step could be the cause of the index error. I'm not sure at the moment what could be the cause of getting 99.9 PQ for each gland, I'll have to look into it.

**Comment by luke2997** [comment]
@meszlili96 I have solved this error now, thank you! EDIT:
I am getting the error when running compute_stats.py. Have you any idea why? 
```
Traceback (most recent call last):
  File "cp_stats.py", line 210, in <module>
    run_nuclei_inst_stat(args.pred_dir, args.true_dir, print_img_stats=False)
  File "cp_stats.py", line 184, in run_nuclei_inst_stat
    metrics[5].append(get_fast_aji(true, pred))
  File "/lustre/home/acct-clsyzs/clsyzs/Luke/hvPan/PanNuke/src/metrics/stats_utils.py", line 56, in get_fast_aji
    paired_pred = np.argmax(pairwise_iou, axis=1)
  File "/lustre/home/acct-clsyzs/clsyzs/.conda/envs/pn36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1037, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/lustre/home/acct-clsyzs/clsyzs/.conda/envs/pn36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
```

I am running the file as below and made no changes to it:
```
python compute_stats.py --pred_dir='/Luke/PanNuke/src/output_pannuke/v1.0/np_hv/' --true_dir='/Luke/PanNuke/src/PanTransform_centroids/fold3/'
```

where pred_dir is .mat files from process.py and true_dir is the .mat files from convert_to_centroids.py

**Comment by meszlili96** [comment]
There's one thing standing out, which would be the `cp_stats.py` file. Where does that come from? Other than that, it actually seems okay what you're doing and I'd expect things to go wrong earlier based on the error message. I'm assuming you've already tried debugging things, but I don't have a better suggestion.

**Comment by dsj-github-account** [comment]
> Hello, I have successfully run train.py and infer.py but after I transform the folds into png and then I get an output file of 2703 files which is used in process.py, I get the following error indicating that there are too many files. I'm wondering if I used the wrong files? My self.inf_data_dir in config is png files from fold3, meanwhile self.inf_output_dir are .mat files.
> 
> ```
> Traceback (most recent call last):
>   File "process.py", line 96, in <module>
>     overlaid_output = visualize_instances(pred_type, img)
>   File "/lustre/home/acct-clsyzs/clsyzs/Luke/hvPan/PanNuke/src/misc/viz_utils.py", line 56, in visualize_instances
>     contours,_ = cv2.findContours(inst_map_crop, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
> ValueError: too many values to unpack (expected 2)
> ```

@luke2997  When I run train.py, I encountered  an error says ' Nan in summary histogram for: param-summary/conv_out_tp/W-histogram', how did you do for this? thanks a lot.
